### ISSUE TITLE
Constant color Bug

### ISSUE THREAD

**Issue by seufernandez** [seufernandez/loki-theme#1]
Constant´s colors turning Blue on Linux distros, happening on both versions...

**Comment by DevRadhy** [comment]
The bug is occurring in the **Kang Edition** version of the theme.

Current color: `#93E6F9`
![Current color](https://user-images.githubusercontent.com/50425715/132967496-27c894ee-f6c7-491a-b438-1fadac62bfa7.png)

Expected color: `#F8F8F2`
![Expected color](https://user-images.githubusercontent.com/50425715/132967525-a8b75c17-c584-4a71-8bc4-398b96be333a.png)

**Comment by seufernandez** [comment]
### We need to fix the classic version as well!

Current color: `#FEC675`
![image](https://user-images.githubusercontent.com/64269128/132967439-51e96586-8118-439b-9d7a-c8cf574a1403.png)

Expected color: `#F8F8F2`
![image](https://user-images.githubusercontent.com/64269128/132967455-32c5be42-cf8f-4200-b78f-0aa263ed5263.png)
